### ISSUE TITLE
Tracking of objects using the Camera and Radar Sensor

### ISSUE THREAD

**Issue by sachinkum0009** [sachinkum0009/carla-multi-sensor-fusion#3]
# Tasks

- [ ] Implement clustering algorithm on the radar sensor and then implement kalman filter for tracking
- [ ] Implement deepsort and yolo algorithm to the tracking of the objects based on the camera sensor
- [ ] Fuse the camera and radar tracking in order to make it more robust
